import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

import { ContextProvider } from "../context/context";
import Provider from "@/context/Provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MyFlixer",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-screen w-screen bg-[#e6eef4] overflow-x-hidden">
          <Provider>
            <ContextProvider>
              <Toaster position="top-center" reverseOrder={false} />
              <Header />
              {children}
            </ContextProvider>
          </Provider>
        </main>
      </body>
    </html>
  );
}
